disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - force_unwrapping
  - implicitly_unwrapped_optional
  - unused_declaration

included:
  - Beacon
  - BeaconTests
  - BeaconUITests

excluded:
  - Beacon/Docs

file_length:
  warning: 400
  error: 600

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 60
  error: 100

line_length:
  warning: 120
  error: 160
